// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdvnfijffyyqanfpxbln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtkdm5maWpmZnl5cWFuZnB4YmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NTIwODEsImV4cCI6MjA1OTAyODA4MX0.I_68KBpXIqKzQtTocbfAYODvhDLJx1ds1yrDcVAaORo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);